version: "3.9"

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-23ai
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "123456"    # contraseña del usuario SYSTEM
      APP_USER: "oracle"           # usuario que quieres crear
      APP_USER_PASSWORD: "123456"  # contraseña del usuario
    volumes:
      - oracle-data:/opt/oracle/oradata   # persistencia de datos

volumes:
  oracle-data:
